version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8860:8860"
    depends_on:
      - db
    environment:
      - PGURL=postgresql://postgres:eueueu@db:5432/platform
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=eueueu
      - POSTGRES_DB=platform
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: